debug:
  description: Debug mode
  type: bool
  env: DEBUG
  value: true

logLevel:
  description: Description of the variable
  type: enum
  env: LOG_LEVEL
  value: DEBUG
  enum:
    - DEBUG
    - INFO
    - WARNING
    - ERROR

project:
  type: struct
  description: Project information
  value:
    name:
      type: string
      value: example-service-api
      description: Name of the project
    title:
      type: string
      value: Example of a service API
      description: Title of the project
    description:
      type: string
      value: Description for an example of a service API
      description: Description of the project
    environment:
      type: enum
      value: DEV
      env: PROJECT_ENV
      enum: [DEV, STG, PROD]
      description: Project environment
