debug:
  description: Debug mode
  type: bool
  env: DEBUG
  value: true

name:
  description: App name
  type: string
  value: "Evald"

age:
  description: Age
  type: uint8
  value: 0

logLevel:
  env: LOG_LEVEL
  type: enum
  value: DEBUG
  description: Description of the variable
  enum:
    - DEBUG
    - INFO
    - WARNING
    - ERROR

project:
  type: struct
  description: Project configuration
  value:
    name:
      type: string
      value: my-service-api
      description: Name of the project
    title:
      type: string
      value: My service API
      description: Title of the project
    description:
      type: string
      value: My service description
      description: Description of the project
    environment:
      type: enum
      value: DEV
      env: PROJECT_ENV
      enum: [DEV, STG, PROD]

grpc:
  type: struct
  value:
    host:
      type: string
      value: 127.0.0.1
      env: GRPC_HOST
    port:
      type: uint16
      value: 50051
      env: GRPC_PORT
    maxConnectionIdle:
      type: int64
      value: 5 # Minutes
      description: MaxConnectionIdle is a duration for the amount of time after which an idle connection would be closed by sending a GoAway.
    maxConnectionAge:
      type: int64
      value: 5 # Minutes
      description: MaxConnectionAge is a duration for the maximum amount of time a connection may exist before it will be closed by sending a GoAway.
    maxConnectionAgeGrace:
      type: int64
      value: 5 # Minutes
      description: MaxConnectionAgeGrace is an additive period after MaxConnectionAge after which the connection will be forcibly closed.
    time:
      type: int64
      value: 15 # Minutes
      description: After a duration of this time if the server doesn't see any activity it pings the client to see if the transport is still alive.
    timeout:
      type: int64
      value: 15 # Seconds
      description: After having pinged for keepalive check, the server waits for a duration of Timeout and if no activity is seen even after that the connection is closed
